#!/usr/bin/env python3
"""
Minimal TRL/Transformers OPD MVP.

This script implements:
1. Student generates on-policy responses.
2. Frozen teacher scores the exact generated trajectories.
3. Student is updated with token-level KL(teacher || student) on response tokens only.
4. Supports Qwen2.5 vocab/head-size mismatch by distilling over shared vocab range.
5. Logs to SwanLab when available; continues without SwanLab if init fails.

Intended default:
- student: Qwen2.5-3B-Instruct
- teacher: Qwen2.5-7B-Instruct
- data: GSM8K parquet generated by verl preprocess script
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path
from typing import Any

import pandas as pd
import torch
import torch.nn.functional as F
from peft import LoraConfig, get_peft_model
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Minimal on-policy distillation MVP")

    parser.add_argument("--student_model", required=True, help="Local path or HF id for student model")
    parser.add_argument("--teacher_model", required=True, help="Local path or HF id for teacher model")
    parser.add_argument("--train_file", required=True, help="Path to train parquet")
    parser.add_argument("--output_dir", required=True, help="Directory for LoRA adapter outputs")

    parser.add_argument("--project_name", default="opd_smoke")
    parser.add_argument("--run_name", default="qwen25_3b_from_7b_gsm8k_trl_opd_mvp")

    parser.add_argument("--max_steps", type=int, default=20)
    parser.add_argument("--batch_size", type=int, default=1)
    parser.add_argument("--max_prompt_length", type=int, default=512)
    parser.add_argument("--max_new_tokens", type=int, default=256)
    parser.add_argument("--lr", type=float, default=1e-5)
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--top_p", type=float, default=0.95)
    parser.add_argument("--top_k", type=int, default=64, help="Teacher top-k tokens used for approximate KL")

    parser.add_argument("--lora_rank", type=int, default=16)
    parser.add_argument("--lora_alpha", type=int, default=32)
    parser.add_argument("--lora_dropout", type=float, default=0.05)

    parser.add_argument("--student_device", default="cuda:0")
    parser.add_argument("--teacher_device", default="cuda:1")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--save_every", type=int, default=10)

    return parser.parse_args()


def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def get_dtype() -> torch.dtype:
    if torch.cuda.is_available() and torch.cuda.is_bf16_supported():
        return torch.bfloat16
    return torch.float16


def maybe_to_python(value: Any) -> Any:
    if hasattr(value, "tolist"):
        return value.tolist()
    return value


def row_to_prompt(row: dict[str, Any], tokenizer) -> str:
    """
    Supports common GSM8K parquet formats:
    - prompt: list[dict] chat messages
    - prompt: string
    - question/problem/input: string
    """
    if "prompt" in row:
        prompt = maybe_to_python(row["prompt"])

        if isinstance(prompt, str):
            return prompt

        if isinstance(prompt, list):
            if len(prompt) > 0 and isinstance(prompt[0], dict):
                return tokenizer.apply_chat_template(
                    prompt,
                    tokenize=False,
                    add_generation_prompt=True,
                )
            return "\n".join(str(x) for x in prompt)

    for key in ("question", "problem", "input"):
        value = row.get(key)
        if isinstance(value, str):
            messages = [{"role": "user", "content": value}]
            return tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )

    raise ValueError(f"Cannot find prompt-like field in row keys: {list(row.keys())}")


def tokenize_prompt(tokenizer, prompt: str, max_prompt_length: int, device: str) -> dict[str, torch.Tensor]:
    encoded = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=max_prompt_length,
        add_special_tokens=False,
    )
    return {key: value.to(device) for key, value in encoded.items()}


def build_lora_student(model, args: argparse.Namespace):
    lora_config = LoraConfig(
        r=args.lora_rank,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()
    return model


def init_swanlab(args: argparse.Namespace):
    try:
        import swanlab

        run = swanlab.init(
            project=args.project_name,
            experiment_name=args.run_name,
            config=vars(args),
        )
        return swanlab, run
    except Exception as exc:
        print(f"[warn] SwanLab init failed; continuing without SwanLab: {exc}")
        return None, None


def save_adapter(student, tokenizer, save_dir: Path) -> None:
    save_dir.mkdir(parents=True, exist_ok=True)
    student.save_pretrained(save_dir)
    tokenizer.save_pretrained(save_dir)
    print(f"[save] {save_dir}")



def compute_response_topk_kl(
    student,
    teacher,
    seq: torch.Tensor,
    prompt_len: int,
    total_len: int,
    common_vocab: int,
    top_k: int,
    temperature: float,
    student_device: str,
    teacher_device: str,
) -> torch.Tensor:
    """
    Approximate KL(teacher || student) on response target tokens only,
    restricted to teacher top-k token ids.

    Causal LM convention:
    - logits[:, t, :] predicts input_ids[:, t + 1].
    - Response target token positions are prompt_len..total_len-1.
    - Corresponding logit indices are prompt_len-1..total_len-2.
    """
    if top_k <= 0:
        raise ValueError("--top_k must be positive")

    start = prompt_len - 1
    end = total_len - 1

    if start < 0 or end <= start:
        raise RuntimeError(
            f"Invalid response logit span: prompt_len={prompt_len}, total_len={total_len}, start={start}, end={end}"
        )

    k = min(top_k, common_vocab)

    student_seq = seq.to(student_device)
    teacher_seq = seq.to(teacher_device)

    with torch.no_grad():
        # Slice to common vocab first so teacher-only padded vocab ids are never selected.
        teacher_response_logits = teacher(teacher_seq).logits[:, start:end, :common_vocab].squeeze(0)
        teacher_topk_logits, teacher_topk_ids = torch.topk(
            teacher_response_logits.float(),
            k=k,
            dim=-1,
        )
        teacher_topk_logits = teacher_topk_logits.to(student_device)
        teacher_topk_ids = teacher_topk_ids.to(student_device)

    # Gather student logits only at teacher-selected top-k ids.
    student_response_logits = student(student_seq).logits[:, start:end, :].squeeze(0)
    student_topk_logits = torch.gather(
        student_response_logits.float(),
        dim=-1,
        index=teacher_topk_ids,
    )

    temp = temperature
    teacher_probs = F.softmax(teacher_topk_logits / temp, dim=-1)
    student_log_probs = F.log_softmax(student_topk_logits / temp, dim=-1)

    loss = F.kl_div(student_log_probs, teacher_probs, reduction="batchmean") * (temp**2)
    return loss


def main() -> None:
    args = parse_args()

    if args.batch_size != 1:
        raise ValueError("This MVP currently supports only --batch_size 1.")

    if args.temperature <= 0:
        raise ValueError("--temperature must be positive.")

    if args.top_k <= 0:
        raise ValueError("--top_k must be positive.")

    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is required for this MVP.")

    set_seed(args.seed)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    dtype = get_dtype()
    print(f"[info] dtype={dtype}")
    print(f"[info] student_device={args.student_device}")
    print(f"[info] teacher_device={args.teacher_device}")
    print(f"[info] top_k={args.top_k}")

    tokenizer = AutoTokenizer.from_pretrained(
        args.student_model,
        trust_remote_code=True,
        use_fast=True,
    )

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    print(f"[info] tokenizer length={len(tokenizer)}")
    print(f"[info] pad_token_id={tokenizer.pad_token_id}")
    print(f"[info] eos_token_id={tokenizer.eos_token_id}")

    student = AutoModelForCausalLM.from_pretrained(
        args.student_model,
        torch_dtype=dtype,
        trust_remote_code=True,
        low_cpu_mem_usage=True,
        attn_implementation="sdpa",
    ).to(args.student_device)

    student.config.use_cache = True
    student = build_lora_student(student, args)
    student.train()

    teacher = AutoModelForCausalLM.from_pretrained(
        args.teacher_model,
        torch_dtype=dtype,
        trust_remote_code=True,
        low_cpu_mem_usage=True,
        attn_implementation="sdpa",
    ).to(args.teacher_device)

    teacher.eval()
    teacher.config.use_cache = True
    for param in teacher.parameters():
        param.requires_grad_(False)

    student_vocab = int(student.get_output_embeddings().weight.shape[0])
    teacher_vocab = int(teacher.get_output_embeddings().weight.shape[0])
    common_vocab = min(student_vocab, teacher_vocab)

    print(f"[info] student vocab/head size={student_vocab}")
    print(f"[info] teacher vocab/head size={teacher_vocab}")
    print(f"[info] common vocab size={common_vocab}")

    if student_vocab != teacher_vocab:
        print(
            f"[warn] vocab/head size mismatch: "
            f"student={student_vocab}, teacher={teacher_vocab}; "
            f"top-k KL will use common_vocab={common_vocab}"
        )

    optimizer = torch.optim.AdamW(student.parameters(), lr=args.lr)

    df = pd.read_parquet(args.train_file)
    if len(df) == 0:
        raise ValueError(f"Empty train file: {args.train_file}")

    df = df.sample(frac=1.0, random_state=args.seed).reset_index(drop=True)
    print(f"[info] loaded train rows={len(df)} from {args.train_file}")

    swanlab, _ = init_swanlab(args)

    progress = tqdm(range(args.max_steps), desc="OPD top-k MVP")

    for step in progress:
        row = df.iloc[step % len(df)].to_dict()
        prompt = row_to_prompt(row, tokenizer)

        prompt_inputs = tokenize_prompt(
            tokenizer=tokenizer,
            prompt=prompt,
            max_prompt_length=args.max_prompt_length,
            device=args.student_device,
        )

        prompt_len = int(prompt_inputs["input_ids"].shape[1])

        student.eval()
        with torch.no_grad():
            generated = student.generate(
                **prompt_inputs,
                max_new_tokens=args.max_new_tokens,
                do_sample=True,
                temperature=args.temperature,
                top_p=args.top_p,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )
        student.train()

        seq = generated.detach()
        total_len = int(seq.shape[1])
        response_len = total_len - prompt_len

        if response_len <= 1:
            print(f"[warn] response too short at step={step}, response_len={response_len}; skip")
            continue

        try:
            loss = compute_response_topk_kl(
                student=student,
                teacher=teacher,
                seq=seq,
                prompt_len=prompt_len,
                total_len=total_len,
                common_vocab=common_vocab,
                top_k=args.top_k,
                temperature=args.temperature,
                student_device=args.student_device,
                teacher_device=args.teacher_device,
            )
        except RuntimeError as exc:
            print(f"[warn] KL computation failed at step={step}: {exc}; skip")
            continue

        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        grad_norm = torch.nn.utils.clip_grad_norm_(student.parameters(), 1.0)
        optimizer.step()

        with torch.no_grad():
            completion_ids = seq[0, prompt_len:]
            completion = tokenizer.decode(completion_ids, skip_special_tokens=True)

        metrics = {
            "train/loss": float(loss.item()),
            "train/grad_norm": float(grad_norm),
            "train/response_len": int(response_len),
            "train/prompt_len": int(prompt_len),
            "train/total_len": int(total_len),
            "train/common_vocab": int(common_vocab),
            "train/student_vocab": int(student_vocab),
            "train/teacher_vocab": int(teacher_vocab),
            "train/top_k": int(args.top_k),
            "train/lr": float(args.lr),
        }

        progress.set_postfix(loss=metrics["train/loss"], response_len=response_len)

        print(
            f"[step {step + 1}/{args.max_steps}] "
            f"loss={metrics['train/loss']:.6f} "
            f"grad_norm={metrics['train/grad_norm']:.4f} "
            f"prompt_len={prompt_len} response_len={response_len}"
        )

        if swanlab is not None:
            swanlab.log(metrics, step=step)

        if (step + 1) % args.save_every == 0:
            save_adapter(student, tokenizer, output_dir / f"step_{step + 1}")

        del loss
        torch.cuda.empty_cache()

    save_adapter(student, tokenizer, output_dir / "final")

    if swanlab is not None:
        try:
            swanlab.finish()
        except Exception:
            pass


if __name__ == "__main__":
    main()
